language: php

php:
  - 7.3
  - 7.4

os: windows

before_scripts:
  - composer install
  - cp .env.example .env
  - php artisan key:generate
  - php artisan jwt:secret

script:
  - vendor/bin/phpunit
